package com.iranmarketai.app;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.text.*;import java.util.*;import java.util.concurrent.*;import org.json.*;
public class MainActivity extends Activity{
 LinearLayout content;TextView status;EditText gateway;SharedPreferences prefs;ChartView chart;Handler handler=new Handler(Looper.getMainLooper()); ExecutorService io=Executors.newSingleThreadExecutor(); Runnable autoRefresh;
 final String[] keys={"TSE","GOLD18","USD","SILVER"};final String[] names={"بورس ایران","طلای ۱۸ عیار","دلار آزاد","نقره"};
 int blue=Color.rgb(21,101,192),green=Color.rgb(27,122,69),red=Color.rgb(190,45,45),gray=Color.rgb(90,90,90);
 public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("settings",0);build();showDashboard(); autoRefresh=()->{ if(content!=null){ loadSummaryAsync(); handler.postDelayed(autoRefresh,60000); } }; handler.postDelayed(autoRefresh,60000);}
 TextView tv(String s,float z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(Color.DKGRAY);t.setPadding(18,10,18,10);return t;}
 Button nav(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);return b;}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(10,6,10,8);root.setBackgroundColor(Color.WHITE);TextView h=tv("Iran Market AI",25);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setTextColor(blue);root.addView(h);root.addView(tv("تحلیل هوشمند بازار ایران • نسخه 1.8 Real Data",13));LinearLayout n=new LinearLayout(this);String[] ns={"داشبورد","نمودار","تحلیل AI","اخبار","تنظیمات"};for(String s:ns){Button x=nav(s);n.addView(x,new LinearLayout.LayoutParams(0,54,1));if(s.equals("داشبورد"))x.setOnClickListener(v->showDashboard());if(s.equals("نمودار"))x.setOnClickListener(v->showChart());if(s.equals("تحلیل AI"))x.setOnClickListener(v->showDeep());if(s.equals("اخبار"))x.setOnClickListener(v->showNews());if(s.equals("تنظیمات"))x.setOnClickListener(v->showSettings());}root.addView(n);status=tv("وضعیت: Demo",12);status.setTextColor(gray);root.addView(status);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 void clear(){content.removeAllViews();}void title(String a,String b){TextView t=tv(a,22);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setTextColor(blue);content.addView(t);content.addView(tv(b,13));}
 void card(String a,String sig,double score,String d){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(12,12,12,12);c.setBackgroundColor(Color.rgb(248,249,251));TextView x=tv(a,19);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);x.setTextColor(blue);c.addView(x);TextView y=tv(sig+"  |  امتیاز: "+String.format(Locale.US,"%.0f",score)+"/100",17);y.setTextColor(sig.equals("BUY")?green:sig.equals("SELL")?red:gray);c.addView(y);c.addView(tv(d,14));content.addView(c);}
 void showDashboard(){clear();title("داشبورد بازار","سیگنال، ریسک، قیمت و وضعیت داده");loadSummaryAsync();Button r=new Button(this);r.setText("↻ بروزرسانی");r.setOnClickListener(v->loadSummaryAsync());content.addView(r);}
 void loadSummaryAsync(){io.execute(()->{try{JSONObject o=new JSONObject(get(base()+"/market/summary"));runOnUiThread(()->{clear();title("داشبورد بازار","سیگنال، ریسک، قیمت و وضعیت داده");try{JSONArray a=o.getJSONArray("assets");for(int i=0;i<a.length();i++){JSONObject x=a.getJSONObject(i);card(nameOf(x.getString("symbol")),x.getString("signal"),x.getDouble("score"),"قیمت: "+x.getDouble("price")+" | تغییر: "+x.getDouble("change_pct")+"% | ریسک: "+x.getString("risk")+" | RSI: "+x.getDouble("rsi14"));}status.setText("داده: "+o.optString("data_mode","demo")+" • "+new SimpleDateFormat("HH:mm:ss",Locale.US).format(new Date()));}catch(Exception e){addDemo();}});}catch(Exception e){runOnUiThread(()->{addDemo();status.setText("Gateway در دسترس نیست • Demo");});}});}
 String base(){return prefs.getString("gateway","http://10.0.2.2:8000").trim().replaceAll("/$","");}String nameOf(String k){for(int i=0;i<keys.length;i++)if(keys[i].equals(k))return names[i];return k;}
 void addDemo(){for(String n:names)card(n,"HOLD",50,"داده Demo — برای داده واقعی Gateway را متصل کنید.");}
 void showChart(){clear();title("نمودار","تاریخچه قیمت");Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));content.addView(sp);chart=new ChartView(this);content.addView(chart,new LinearLayout.LayoutParams(-1,430));Button b=new Button(this);b.setText("دریافت تاریخچه");content.addView(b);b.setOnClickListener(v->loadChart(keys[sp.getSelectedItemPosition()]));loadChart("GOLD18");}
 void loadChart(String symbol){try{JSONArray a=new JSONArray(get(base()+"/market/candles/"+symbol+"?limit=120"));ArrayList<Double> vals=new ArrayList<>();for(int i=0;i<a.length();i++)vals.add(a.getJSONObject(i).getDouble("c"));chart.setValues(vals);status.setText("History • "+symbol);}catch(Exception e){ArrayList<Double>d=new ArrayList<>();for(int i=0;i<60;i++)d.add(100.0+i+(i%7)*.7);chart.setValues(d);status.setText("History Demo");}}
 void showDeep(){clear();title("تحلیل AI","امتیاز چندعاملی + ورود/حدضرر/اهداف");Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));content.addView(sp);Button go=new Button(this);go.setText("اجرای تحلیل");content.addView(go);go.setOnClickListener(v->deep(keys[sp.getSelectedItemPosition()],names[sp.getSelectedItemPosition()]));deep("GOLD18","طلای ۱۸ عیار");}
 void deep(String key,String name){try{JSONObject o=new JSONObject(get(base()+"/market/analyze/"+key));card(name,o.getString("signal"),o.getDouble("score"),"ریسک: "+o.getString("risk")+" • منبع: "+o.getString("source"));content.addView(tv("قیمت: "+o.getDouble("price")+" | تغییر: "+o.getDouble("change_pct")+"%",15));content.addView(tv("RSI14: "+o.getDouble("rsi14")+" | EMA20: "+o.getDouble("ema20")+" | EMA50: "+o.getDouble("ema50"),15));content.addView(tv("Momentum: "+o.getDouble("momentum")+"% | تغییر حجم: "+o.getDouble("volume_change")+"%",15));content.addView(tv("ورود: "+o.getDouble("entry")+" | حدضرر: "+o.getDouble("stop")+"",15));content.addView(tv("هدف ۱: "+o.getDouble("target1")+" | هدف ۲: "+o.getDouble("target2"),15));}catch(Exception e){Toast.makeText(this,"Gateway وصل نیست",Toast.LENGTH_SHORT).show();}}
 void showNews(){clear();title("اخبار و احساسات","News/Sentiment Provider");for(String k:keys){try{JSONArray a=new JSONArray(get(base()+"/news/"+k));JSONObject n=a.getJSONObject(0);content.addView(tv(nameOf(k)+" — "+n.getString("title")+" | "+n.getString("sentiment"),15));}catch(Exception e){content.addView(tv(nameOf(k)+" — منبع خبر Demo",15));}}}
 void showSettings(){clear();title("تنظیمات","Gateway و بروزرسانی خودکار");gateway=new EditText(this);gateway.setHint("http://10.0.2.2:8000");gateway.setText(base());content.addView(gateway);Button b=new Button(this);b.setText("ذخیره و تست اتصال");b.setOnClickListener(v->{prefs.edit().putString("gateway",gateway.getText().toString().trim()).apply();try{JSONObject h=new JSONObject(get(base()+"/health"));status.setText("متصل • "+h.optString("version")+" • "+h.optString("provider"));Toast.makeText(this,"اتصال موفق",Toast.LENGTH_SHORT).show();}catch(Exception e){status.setText("اتصال ناموفق");Toast.makeText(this,"Gateway در دسترس نیست",Toast.LENGTH_SHORT).show();}});content.addView(b);content.addView(tv("حالت LIVE فقط وقتی فعال می‌شود که Gateway به Data Provider معتبر متصل باشد. حالت Demo برای تست رابط کاربری است.",13));content.addView(tv("نسخه: 2.0.0 Production • بروزرسانی خودکار هر ۶۰ ثانیه",13));}
 protected void onDestroy(){handler.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}
 String get(String u)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(3500);c.setReadTimeout(7000);c.setRequestMethod("GET");int code=c.getResponseCode();if(code<200||code>=300)throw new IOException("HTTP "+code);BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);r.close();c.disconnect();return s.toString();}
}